# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcmean <- function(x, margin) {
    .Call(`_mixR_rcmean`, x, margin)
}

rcsum <- function(x, margin) {
    .Call(`_mixR_rcsum`, x, margin)
}

expZ_norm_C <- function(x, pi, mu, sd) {
    .Call(`_mixR_expZ_norm_C`, x, pi, mu, sd)
}

loglik_norm_C <- function(x, pi, mu, sd) {
    .Call(`_mixR_loglik_norm_C`, x, pi, mu, sd)
}

norm_uv <- function(x, pi, mu, sd, max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_norm_uv`, x, pi, mu, sd, max_iter, tol)
}

norm_ev <- function(x, pi, mu, sd, max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_norm_ev`, x, pi, mu, sd, max_iter, tol)
}

enorm_trunc <- function(a, b, mu = 0, sd = 1) {
    .Call(`_mixR_enorm_trunc`, a, b, mu, sd)
}

exnorm <- function(data, mu, sd) {
    .Call(`_mixR_exnorm`, data, mu, sd)
}

txnorm <- function(pi, mu, sd, ex) {
    .Call(`_mixR_txnorm`, pi, mu, sd, ex)
}

loglik_norm_gC <- function(data, pi, mu, sd) {
    .Call(`_mixR_loglik_norm_gC`, data, pi, mu, sd)
}

norm_uv_g <- function(data, pi, mu, sd, max_iter = 100L, tol = 1e-4) {
    .Call(`_mixR_norm_uv_g`, data, pi, mu, sd, max_iter, tol)
}

norm_ev_g <- function(data, pi, mu, sd, max_iter = 1000L, tol = 1e-4) {
    .Call(`_mixR_norm_ev_g`, data, pi, mu, sd, max_iter, tol)
}

expZ_gamma_C <- function(x, pi, alpha, lambda) {
    .Call(`_mixR_expZ_gamma_C`, x, pi, alpha, lambda)
}

loglik_gamma_C <- function(x, pi, alpha, lambda) {
    .Call(`_mixR_loglik_gamma_C`, x, pi, alpha, lambda)
}

gamma_bisection_C <- function(n, ex, tx, tol = 1e-4, max_iter = 100L, xleft = 0.1, xright = 5) {
    .Call(`_mixR_gamma_bisection_C`, n, ex, tx, tol, max_iter, xleft, xright)
}

to_mu_sd_gamma_C <- function(alpha, lambda) {
    .Call(`_mixR_to_mu_sd_gamma_C`, alpha, lambda)
}

to_alpha_lambda_gamma_C <- function(mu, sd) {
    .Call(`_mixR_to_alpha_lambda_gamma_C`, mu, sd)
}

gamma_C <- function(x, pi, alpha, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_gamma_C`, x, pi, alpha, lambda, method, max_iter, tol)
}

egamma_trunc <- function(a, b, alpha, lambda) {
    .Call(`_mixR_egamma_trunc`, a, b, alpha, lambda)
}

EXgamma_C <- function(data, alpha, lambda) {
    .Call(`_mixR_EXgamma_C`, data, alpha, lambda)
}

TXgamma_C <- function(pi, alpha, lambda, ex) {
    .Call(`_mixR_TXgamma_C`, pi, alpha, lambda, ex)
}

loglik_gamma_g_C <- function(data, pi, alpha, lambda) {
    .Call(`_mixR_loglik_gamma_g_C`, data, pi, alpha, lambda)
}

gamma_g_C <- function(data, pi, alpha, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_gamma_g_C`, data, pi, alpha, lambda, method, max_iter, tol)
}

expZ_weib_C <- function(x, pi, k, lambda) {
    .Call(`_mixR_expZ_weib_C`, x, pi, k, lambda)
}

loglik_weib_C <- function(x, pi, k, lambda) {
    .Call(`_mixR_loglik_weib_C`, x, pi, k, lambda)
}

g_weib <- function(r, n, ex, tx) {
    .Call(`_mixR_g_weib`, r, n, ex, tx)
}

newton_weib_C <- function(n, ex, tx, r = 1, max_iter = 100L) {
    .Call(`_mixR_newton_weib_C`, n, ex, tx, r, max_iter)
}

weib_bisection_C <- function(n, ex, tx, tol = 1e-4, max_iter = 100L, xleft = 0.1, xright = 5) {
    .Call(`_mixR_weib_bisection_C`, n, ex, tx, tol, max_iter, xleft, xright)
}

to_mu_sd_weib_C <- function(k, lambda) {
    .Call(`_mixR_to_mu_sd_weib_C`, k, lambda)
}

to_k_lambda_weib_C <- function(mu, sd) {
    .Call(`_mixR_to_k_lambda_weib_C`, mu, sd)
}

weib_C <- function(x, pi, k, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_weib_C`, x, pi, k, lambda, method, max_iter, tol)
}

eweib_trunc <- function(a, b, k, lambda) {
    .Call(`_mixR_eweib_trunc`, a, b, k, lambda)
}

EXweib_C <- function(data, k, lambda) {
    .Call(`_mixR_EXweib_C`, data, k, lambda)
}

TXweib_C <- function(pi, k, lambda, ex) {
    .Call(`_mixR_TXweib_C`, pi, k, lambda, ex)
}

loglik_weib_g_C <- function(data, pi, k, lambda) {
    .Call(`_mixR_loglik_weib_g_C`, data, pi, k, lambda)
}

weib_g_C <- function(data, pi, k, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_weib_g_C`, data, pi, k, lambda, method, max_iter, tol)
}

expZ_lnorm_C <- function(x, pi, mulog, sdlog) {
    .Call(`_mixR_expZ_lnorm_C`, x, pi, mulog, sdlog)
}

loglik_lnorm_C <- function(x, pi, mulog, sdlog) {
    .Call(`_mixR_loglik_lnorm_C`, x, pi, mulog, sdlog)
}

lnorm_C <- function(x, pi, mulog, sdlog, max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_lnorm_C`, x, pi, mulog, sdlog, max_iter, tol)
}

elnorm_trunc <- function(a, b, mulog, sdlog) {
    .Call(`_mixR_elnorm_trunc`, a, b, mulog, sdlog)
}

EXlnorm_C <- function(data, mulog, sdlog) {
    .Call(`_mixR_EXlnorm_C`, data, mulog, sdlog)
}

TXlnorm_C <- function(pi, mulog, sdlog, ex) {
    .Call(`_mixR_TXlnorm_C`, pi, mulog, sdlog, ex)
}

loglik_lnorm_g_C <- function(data, pi, mulog, sdlog) {
    .Call(`_mixR_loglik_lnorm_g_C`, data, pi, mulog, sdlog)
}

lnorm_g_C <- function(data, pi, mulog, sdlog, max_iter = 500L, tol = 1e-6) {
    .Call(`_mixR_lnorm_g_C`, data, pi, mulog, sdlog, max_iter, tol)
}

